// sso/vue/src/App.vue
<template>
  <h1>vue3</h1>
</template>

<script setup lang='ts'>
//如果有token代表登录过了 如果没有跳转到 登录页面也就是SSO 那个页面，并且地址栏携带AppID
const token = new URLSearchParams(location.search).get('token')
if (!token) {
  fetch('http://localhost:3000/login?appId=Rs6s2aHi').then(res => {
    console.log('res:::----->', res)
    location.href = res.url
  })
}
</script>

<style></style>

// sso/react/src/App.jsx
import { useState } from 'react'
import './App.css'
function App() {
  const [count, setCount] = useState(0)
  //逻辑其实一样的只是区分了不用应用的AppId
  const token = location.search.split('=')[1]
  if (!token) {
      fetch('http://localhost:3000/login?appId=9LQ8Y3mB').then(res => {
          location.href = res.url
      })
  }
  return (
    <>
     <h1>react19</h1>
    </>
  )
}
export default App
